In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

import pandas as pd
import on_islem as on


In [3]:
df = pd.read_csv("data/nlp.csv", index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [5]:
df["Text_2"] = df["Text"].apply(on.pre_processing)
df["Text_2"] = df["Text_2"].apply(on.remove_space)
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...  
1  [veri, analiz, edin:, chatgpt'yi, kullanarak, ...  
2  [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...  
3  [., baidu, research:, çin', ön, gele, ara, mot...  
4  [., microsoft, ai:, microsoft', yapay, zeka, t...

In [8]:
df[df["Text_2"].str[0].isnull()]


Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
464  #investment #software #technology #tech #innov...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [10]:
df_index = df[df["Text_2"].str[0].isnull()].index
df = df.drop(df_index)
df = df.reset_index()

del df["index"]

df[df["Text_2"].str[0].isnull()]


Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [11]:
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...  
1  [veri, analiz, edin:, chatgpt'yi, kullanarak, ...  
2  [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...  
3  [., baidu, research:, çin', ön, gele, ara, mot...  
4  [., microsoft, ai:, microsoft', yapay, zeka, t...

In [12]:
df["Text_2"]

0      [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...
1      [veri, analiz, edin:, chatgpt'yi, kullanarak, ...
2      [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...
3      [., baidu, research:, çin', ön, gele, ara, mot...
4      [., microsoft, ai:, microsoft', yapay, zeka, t...
                             ...                        
850    [doğal, dil, işle, alan, yük, lisans-doktor, y...
851                                   [dogal, dil, isle]
852       [ver, madencilik, doğal, dil, işle, uygulamas]
853    ["doğal, dil, işleme", il, ilgil, deney, ola, ...
854    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 855, dtype: object

In [14]:
df["Text_3"] = [' '.join(w for w in item) for item in df["Text_2"]]
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...   
1    [veri, analiz, edin:, chatgpt'yi, kullanarak, ...   
2    [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...   
3    [., baidu, research:, çin', ön, gele, ara, mot...   
4    [., microsoft, ai:, microsoft', yapay, zeka, t...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisans-doktor, y...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  ["doğal, dil, işleme", il, ilgil, deney, ola, ...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir, i̇şe yarar? yapay zeka (yz) ...  
1    veri analiz edin: chatgpt'yi kullanarak doğal ...  
2    öncelik yapay zeka olduğunu, iç önemli olduk k...  
3    . baidu research: çin' ön gele ara motor baidu...  
4    . microsoft ai: microsoft' yapay zeka teknoloj...  
..                                                 ...  
850  doğal dil işle alan yük lisans-doktor yapa dan...  
851                                     dogal dil isle  
852            ver madencilik doğal dil işle uygulamas  
853  "doğal dil işleme" il ilgil deney ola yazılımc...  
854  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[855 rows x 3 columns]

In [16]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())
X

<855x4718 sparse matrix of type '<class 'numpy.int64'>'
	with 16748 stored elements in Compressed Sparse Row format>

In [17]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
X[0]

<1x4718 sparse matrix of type '<class 'numpy.int64'>'
	with 27 stored elements in Compressed Sparse Row format>

In [21]:
df["Text_4"] = X.toarray().tolist()
df.head()

Text  \
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  \
0  [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...   
1  [veri, analiz, edin:, chatgpt'yi, kullanarak, ...   
2  [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...   
3  [., baidu, research:, çin', ön, gele, ara, mot...   
4  [., microsoft, ai:, microsoft', yapay, zeka, t...   

                                              Text_3  \
0  yapay zeka nedir, i̇şe yarar? yapay zeka (yz) ...   
1  veri analiz edin: chatgpt'yi kullanarak doğal ...   
2  öncelik yapay zeka olduğunu, iç önemli olduk k...   
3  . baidu research: çin' ön gele ara motor baidu...   
4  . microsoft ai: microsoft' yapay zeka teknoloj...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

TF-IDF

In [27]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df["Text_3"].tolist())
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [29]:
set(X.toarray()[0])

{0.0,
 0.03561584738033964,
 0.0370186462346595,
 0.1253403997395551,
 0.13098588371458336,
 0.13167497199873748,
 0.15200319802111156,
 0.1574722789655854,
 0.15898847124200371,
 0.16223937852049639,
 0.17693282805810528,
 0.17966298155797683,
 0.1934928733264094,
 0.20330533769428094,
 0.2095240907931046,
 0.21201151929838585,
 0.21713522946271355,
 0.22504696162121715,
 0.22694769383058502,
 0.24077758559901766,
 0.3193427047420363}

In [31]:
df["Text_5"] = X.toarray().tolist()
df

Text  \
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...   
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
850  doğal dil işleme alanında yüksek lisans-doktor...   
851                           dogal dil isleme şeyleri   
852  Bir veri madenciliği ve doğal dil işleme uygul...   
853  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
854  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2  \
0    [yapay, zeka, nedir,, i̇şe, yarar?, yapay, zek...   
1    [veri, analiz, edin:, chatgpt'yi, kullanarak, ...   
2    [öncelik, yapay, zeka, olduğunu,, iç, önemli, ...   
3    [., baidu, research:, çin', ön, gele, ara, mot...   
4    [., microsoft, ai:, microsoft', yapay, zeka, t...   
..                                                 ...   
850  [doğal, dil, işle, alan, yük, lisans-doktor, y...   
851                                 [dogal, dil, isle]   
852     [ver, madencilik, doğal, dil, işle, uygulamas]   
853  ["doğal, dil, işleme", il, ilgil, deney, ola, ...   
854  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  \
0    yapay zeka nedir, i̇şe yarar? yapay zeka (yz) ...   
1    veri analiz edin: chatgpt'yi kullanarak doğal ...   
2    öncelik yapay zeka olduğunu, iç önemli olduk k...   
3    . baidu research: çin' ön gele ara motor baidu...   
4    . microsoft ai: microsoft' yapay zeka teknoloj...   
..                                                 ...   
850  doğal dil işle alan yük lisans-doktor yapa dan...   
851                                     dogal dil isle   
852            ver madencilik doğal dil işle uygulamas   
853  "doğal dil işleme" il ilgil deney ola yazılımc...   
854  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4  \
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
850  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
850  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[855 rows x 5 columns]

In [32]:
len(X.toarray()[0])

4718